### ISSUE TITLE
Plugin 개발

### ISSUE THREAD

**Issue by ollybaysion** [ollybaysion/audio-mastering#6]
## TODO
- [ ] Compressor => linux-studio-plugin plugins/compressor.cpp
- [ ] De-esser => calf src/modules_comp.cpp
- [ ] EQ => linux-studio-plugin plugins/para_equalizer.cpp
- [ ] Gate => linux-studio-plugin plguins/gate.cpp
- [ ] Stereo Tools => calf src/modules_tools.cpp

- [ ] https://github.com/michaelwillis/dragonfly-reverb
- [ ] https://github.com/szkkng/simple-reverb
