### ISSUE TITLE
lsp / calf C++ 라이브러리 작업

### ISSUE THREAD

**Issue by ollybaysion** [ollybaysion/audio-mastering#7]
## TODO
- [x] lsp 코드 리뷰
- [x] calf 코드 리뷰
- [x] 문제 정의 및 플러그인 개발

## Comment
- #6

**Comment by ollybaysion** [comment]
## lsp 코드 리뷰
https://github.com/lsp-plugins/lsp-plugins/tree/lsp-plugins-1.1.26
- 버전: 1.1.26 (released 2020, 09)
- src 위치: src/core
- include 위치: include/core

### 리스트
1. Dynamics
- Compressor (dynamics/Compressor.cpp)
- Dynamic Processor (dynamics/DynamicProcessor.cpp)
- Expander (dynamics/Expander.cpp)
- Gate (dynamics/Gate.cpp)
- Limiter (dynamics/Limiter.cpp)

2. Filters
- Equalizer (filters/Eqaulizer.cpp)

### TODO
- JNI 라이브러리화
- 각 오디오 프로세서 별 파라미터 정리

**Comment by ollybaysion** [comment]
## calf 코드 리뷰
https://github.com/calf-studio-gear/calf

### 리스트
#### De-Esser
- src/modules_comp.cpp

#### Stereo
- src/module_tools.cpp

### TODO
- JNI 라이브러리화
- 각 오디오 프로세서 별 파라미터 정리 (동작 과정)
