### ISSUE TITLE
Step 1 - 오디오 마스터링 AI 진단 문제 정의

### ISSUE THREAD

**Issue by ollybaysion** [ollybaysion/audio-mastering#8]
## TODO
- [ ] (1) Waveform 분석
- [ ] (2) Mel-Spectogram 분석
- [ ] (3) 종합 점수 체계 정의 (M-Score)
- [ ] 추가적인 문제 정의
- [ ] AI 모델 (분류 / Feature Extraction 등)
