### ISSUE TITLE
Step 2 - 마스터링 솔루션 기능

### ISSUE THREAD

**Issue by ollybaysion** [ollybaysion/audio-mastering#9]
## TODO
- [ ] Step 1 결과에서 필요한 플러그인 정리
- [ ] 솔루션을 5가지 카테고리로 분류
- [ ] Parameter의 경우 Pre-Setting 되어 있는 값을 사용
